# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import graph_pb2 as graph__pb2


class DirectGraphDistanceServiceStub(object):
    """定义接口HelloService
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DirectGraphDistance = channel.unary_unary(
                '/graphtool.DirectGraphDistanceService/DirectGraphDistance',
                request_serializer=graph__pb2.Graph.SerializeToString,
                response_deserializer=graph__pb2.GraphStats.FromString,
                )


class DirectGraphDistanceServiceServicer(object):
    """定义接口HelloService
    """

    def DirectGraphDistance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DirectGraphDistanceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DirectGraphDistance': grpc.unary_unary_rpc_method_handler(
                    servicer.DirectGraphDistance,
                    request_deserializer=graph__pb2.Graph.FromString,
                    response_serializer=graph__pb2.GraphStats.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'graphtool.DirectGraphDistanceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DirectGraphDistanceService(object):
    """定义接口HelloService
    """

    @staticmethod
    def DirectGraphDistance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/graphtool.DirectGraphDistanceService/DirectGraphDistance',
            graph__pb2.Graph.SerializeToString,
            graph__pb2.GraphStats.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
