# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graph.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgraph.proto\x12\tgraphtool\"*\n\x04\x45\x64ge\x12\x10\n\x08sourceID\x18\x01 \x01(\x03\x12\x10\n\x08targetID\x18\x02 \x01(\x03\"\'\n\x05Graph\x12\x1e\n\x05\x65\x64ges\x18\x01 \x03(\x0b\x32\x0f.graphtool.Edge\"\x1f\n\rFrequencyItem\x12\x0e\n\x06values\x18\x01 \x03(\x03\"\xb5\x01\n\nGraphStats\x12\x11\n\tedgeCount\x18\x01 \x01(\x03\x12\x11\n\tnodeCount\x18\x02 \x01(\x03\x12\x11\n\tpathCount\x18\x03 \x01(\x03\x12\x15\n\rdistanceCount\x18\x04 \x01(\x03\x12\x0b\n\x03\x41SD\x18\x05 \x01(\x01\x12\x11\n\tEnableAsd\x18\x06 \x01(\x08\x12\n\n\x02\x43\x43\x18\x07 \x01(\x01\x12+\n\tfrequency\x18\x08 \x03(\x0b\x32\x18.graphtool.FrequencyItem2\\\n\x1a\x44irectGraphDistanceService\x12>\n\x13\x44irectGraphDistance\x12\x10.graphtool.Graph\x1a\x15.graphtool.GraphStatsB\rZ\x0b./graphtoolb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'graph_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\013./graphtool'
  _EDGE._serialized_start=26
  _EDGE._serialized_end=68
  _GRAPH._serialized_start=70
  _GRAPH._serialized_end=109
  _FREQUENCYITEM._serialized_start=111
  _FREQUENCYITEM._serialized_end=142
  _GRAPHSTATS._serialized_start=145
  _GRAPHSTATS._serialized_end=326
  _DIRECTGRAPHDISTANCESERVICE._serialized_start=328
  _DIRECTGRAPHDISTANCESERVICE._serialized_end=420
# @@protoc_insertion_point(module_scope)
